### ISSUE TITLE
Codes not working

### ISSUE THREAD

**Issue by kxbandeli** [aaronrudkin/GabScraper#4]
First of all, thank you for the programs to crawl gab site. Much appreciated!!

I ran into a couple of issues.

1. I was not able to execute the program: scrape_posts.py. It gives me the following error. Any help here would be great.
======
Traceback (most recent call last):
  File "C:\Users\kxbandeli\workspace\test\gtest\scrape_posts.py", line 176, in <module>
    process_args()
  File "C:\Users\kxbandeli\workspace\test\gtest\scrape_posts.py", line 167, in process_args
    browser = login(args["username"], args["password"])
  File "C:\Users\kxbandeli\workspace\test\gtest\scrape_posts.py", line 46, in login
    browser["username"] = username
  File "C:\Python27\lib\site-packages\mechanize\_form_controls.py", line 1945, in __setitem__
    control = self.find_control(name)
  File "C:\Python27\lib\site-packages\mechanize\_form_controls.py", line 2331, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "C:\Python27\lib\site-packages\mechanize\_form_controls.py", line 2424, in _find_control
    raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'username'
====

2. Even for the program scrape_users.py, I see the below error. Any help would be very much appreciated.
====
Traceback (most recent call last):
  File "C:\Users\kxbandeli\workspace\test\gtest\scrape_users.py", line 196, in <module>
    process_args()
  File "C:\Users\kxbandeli\workspace\test\gtest\scrape_users.py", line 184, in process_args
    user_names = [x.strip() for x in open(args["filename"], "r").read().split("\n") if len(x.strip())]
IOError: [Errno 2] No such file or directory: 'names.txt'
====

Again, thank you very much!

**Comment by MastaBaba** [comment]
Problem 1 is resolved here:

https://github.com/aaronrudkin/GabScraper/issues/1
